name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure SSH
        env:
          AWS_KEY: ${{ secrets.AWS_KEY }}
          AWS_HOST: ${{ secrets.AWS_HOST }}
        run: |
          mkdir -p ~/.ssh
          echo "$AWS_KEY" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $AWS_HOST >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Deploy to EC2
        env:
          AWS_HOST: ${{ secrets.AWS_HOST }}
          AWS_USER: ${{ secrets.AWS_USER }}
        run: |
          # 앱 디렉토리 생성
          ssh $AWS_USER@$AWS_HOST 'mkdir -p /home/ec2-user/app'
          
          # 파일 전송 및 배포
          scp -r ./* $AWS_USER@$AWS_HOST:/home/ec2-user/app
          ssh $AWS_USER@$AWS_HOST << 'EOF'
            cd /home/ec2-user/app

            # .env 파일 생성
            cat <<EOT > .env
            PORT=${{ secrets.PORT }}
            DB_HOST=${{ secrets.DB_HOST }}
            DB_USER=${{ secrets.DB_USER }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            DB_DB=${{ secrets.DB_DB }}

            BASIC_AUTH_USER=${{ secrets.BASIC_AUTH_USER }}
            BASIC_AUTH_PASSWORD=${{ secrets.BASIC_AUTH_PASSWORD }}

            AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_BUCKET_NAME=${{ secrets.AWS_BUCKET_NAME }}
            AWS_REGION=${{ secrets.AWS_REGION }}
            EOT
            npm install
            pm2 restart all || pm2 start src/server.js --name "jaksim-chat"
          EOF
